/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeoplePersonIdRouteImport } from './routes/people/$personId'
import { Route as MoviesMovieIdRouteRouteImport } from './routes/movies/$movieId/route'
import { Route as MoviesMovieIdDetailsRouteImport } from './routes/movies/$movieId/details'
import { Route as MoviesMovieIdCreditsRouteImport } from './routes/movies/$movieId/credits'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRouteRoute = MoviesMovieIdRouteRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdDetailsRoute = MoviesMovieIdDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => MoviesMovieIdRouteRoute,
} as any)
const MoviesMovieIdCreditsRoute = MoviesMovieIdCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => MoviesMovieIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/movies/$movieId': typeof MoviesMovieIdRouteRouteWithChildren
  '/people/$personId': typeof PeoplePersonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/movies/$movieId/credits': typeof MoviesMovieIdCreditsRoute
  '/movies/$movieId/details': typeof MoviesMovieIdDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/movies/$movieId': typeof MoviesMovieIdRouteRouteWithChildren
  '/people/$personId': typeof PeoplePersonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/movies/$movieId/credits': typeof MoviesMovieIdCreditsRoute
  '/movies/$movieId/details': typeof MoviesMovieIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/movies/$movieId': typeof MoviesMovieIdRouteRouteWithChildren
  '/people/$personId': typeof PeoplePersonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/movies/$movieId/credits': typeof MoviesMovieIdCreditsRoute
  '/movies/$movieId/details': typeof MoviesMovieIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/movies/$movieId'
    | '/people/$personId'
    | '/api/auth/$'
    | '/movies/$movieId/credits'
    | '/movies/$movieId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/movies/$movieId'
    | '/people/$personId'
    | '/api/auth/$'
    | '/movies/$movieId/credits'
    | '/movies/$movieId/details'
  id:
    | '__root__'
    | '/'
    | '/signup'
    | '/movies/$movieId'
    | '/people/$personId'
    | '/api/auth/$'
    | '/movies/$movieId/credits'
    | '/movies/$movieId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignupRoute: typeof SignupRoute
  MoviesMovieIdRouteRoute: typeof MoviesMovieIdRouteRouteWithChildren
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId/details': {
      id: '/movies/$movieId/details'
      path: '/details'
      fullPath: '/movies/$movieId/details'
      preLoaderRoute: typeof MoviesMovieIdDetailsRouteImport
      parentRoute: typeof MoviesMovieIdRouteRoute
    }
    '/movies/$movieId/credits': {
      id: '/movies/$movieId/credits'
      path: '/credits'
      fullPath: '/movies/$movieId/credits'
      preLoaderRoute: typeof MoviesMovieIdCreditsRouteImport
      parentRoute: typeof MoviesMovieIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MoviesMovieIdRouteRouteChildren {
  MoviesMovieIdCreditsRoute: typeof MoviesMovieIdCreditsRoute
  MoviesMovieIdDetailsRoute: typeof MoviesMovieIdDetailsRoute
}

const MoviesMovieIdRouteRouteChildren: MoviesMovieIdRouteRouteChildren = {
  MoviesMovieIdCreditsRoute: MoviesMovieIdCreditsRoute,
  MoviesMovieIdDetailsRoute: MoviesMovieIdDetailsRoute,
}

const MoviesMovieIdRouteRouteWithChildren =
  MoviesMovieIdRouteRoute._addFileChildren(MoviesMovieIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignupRoute: SignupRoute,
  MoviesMovieIdRouteRoute: MoviesMovieIdRouteRouteWithChildren,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
